language: generic

sudo: required

services: 
  - docker

branches:
  only:
    - main

script:

  - docker build -t wngusrud27/docker-frontend ./frontend
  - docker build -t wngusrud27/docker-backend ./backend
  - docker build -t wngusrud27/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push wngusrud27/docker-frontend 
  - docker push wngusrud27/docker-backend 
  - docker push wngusrud27/docker-nginx 



