language: generic

jdk: oraclejdk11

sudo: required

env: SPRING_PROFILES_ACTIVE=prod

cache:
  directories:
  - .autoconf
  - $HOME/.m2

services: 
  - docker


before_install: 
  - cd backend
#  - sudo wget https://services.gradle.org/distributions/gradle-6.8-bin.zip
#  - sudo unzip -qq gradle-6.8-bin.zip
#  - export GRADLE_HOME=$PWD/gradle-6.8
#  - export PATH=$GRADLE_HOME/bin:$PATH
#  - gradle -version
#  - gradle wrap
  - chmod +x ./gradlew

script:
  # BUILD
  - ./gradlew build
  - cd ../

after_success:
  - docker build -t wngusrud27/docker-frontend ./frontend
  - docker build -t wngusrud27/docker-backend ./backend
  - docker build -t wngusrud27/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push wngusrud27/docker-frontend 
  - docker push wngusrud27/docker-backend 
  - docker push wngusrud27/docker-nginx 

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "ybo-phase1-app"
  env: Ybophase1-env
  bucket_name: elasticbeanstalk-ap-northeast-2-895948757088 
  bucket_path: "ybo-phase1-app"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key_id: $AWS_SECRET_ACCESS_KEY


