language: generic

jdk: oraclejdk11

sudo: required

cache:
  directories:
  - .autoconf
  - $HOME/.m2

services: 
  - docker

branches:
  only:
    - main

before_install: 
  - cd backend
  - sudo wget https://services.gradle.org/distributions/gradle-6.8-bin.zip
  - sudo unzip -qq gradle-6.8-bin.zip
  - export GRADLE_HOME=$PWD/gradle-6.8
  - export PATH=$GRADLE_HOME/bin:$PATH
  - gradle -version
  - gradle wrap
  - chmod +x ./gradlew

script:
  # BUILD
  - ./gradlew build

after_success:
  - cd ../
  - docker build -t wngusrud27/docker-frontend ./frontend
  - docker build -t wngusrud27/docker-backend ./backend
  - docker build -t wngusrud27/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push wngusrud27/docker-frontend 
  - docker push wngusrud27/docker-backend 
  - docker push wngusrud27/docker-nginx 



