version: '3'
services:
  frontend: 
    build: 
      dockerfile: Dockerfile.dev
      context: ./frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true

  nginx:
    restart: always
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports: 
      - "3000:80"
    depends_on:
      - frontend
      - backend

  backend:
    build: 
      dockerfile: Dockerfile
      context: ./backend
    container_name: app_backend
    volumes: 
      - ./backend:/app
    environment:
      SPRING_PROFILES_ACTIVE: prod
      SPRING_DATASOURCE_URL: jdbc:mysql://172.18.0.1:3307/ybo_db?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true&characterEncoding=UTF-8
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    depends_on:
      - mysql

  flask:
    build: 
      dockerfile: Dockerfile
      context: ./flask
    container_name: app_flask

  mysql:
    build: ./mysql
    restart: unless-stopped
    container_name: app_mysql
    ports:
    - "3307:3306"
    volumes: 
    - ./mysql/mysql_data:/var/lib/mysql
    - ./mysql/sqls/:/docker-entrypoint-initdb.d/
    environment:
      MYSQL_ROOT_PASSWORD: 1234
      MYSQL_DATABASE: ybo_db


# 실행: docker-compose -f docker-compose-local.yml up 