version: '2.4'
services:
  frontend: 
    image: wngusrud27/docker-frontend
    volumes:
      - /app/node_modules
      - ./frontend:/app
    mem_limit: 128m

  nginx:
    restart: always
    image: wngusrud27/docker-nginx
    ports: 
      - "80:80"
    mem_limit: 128m
    links:
      - frontend
      - backend

  backend:
    image: wngusrud27/docker-backend
    container_name: app_backend
    volumes: 
      - ./backend:/app
    # environment:
    #   SPRING_PROFILES_ACTIVE: prod
    mem_limit: 128m

