server:
  port: '8088'
  use-forward-headers: true

logging:
  level:
    org:
      hibernate:
        SQL: debug
request:
  logging: false
decorator:
  datasource:
    p6spy:
      enable-logging: false


spring:
  profiles:
    active: local
  mvc:
    throw-exception-if-no-handler-found: true

restTemplate:
  factory:
    readTimeout: 5000
    connectTimeout: 3000
  httpClient:
    maxConnTotal: 100
    maxConnPerRoute: 5

flask:
  server:
    url: http://${flask.server.ip}:5000
---

spring:
  config:
    activate:
      on-profile: prod
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5Dialect
    generate-ddl: true
    show-sql: true

---
spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: ${DB_URL}
    username: root
    password: 12341234
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true

flask:
  server:
    ip: 127.0.0.1

---
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/test
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    generate-ddl: true
    show-sql: true

flask:
  server:
    ip: 127.0.0.1